# Sylius TaxonGallery Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>

madcoders_taxon_gallery_credits:
    path: /madcoders/taxon_gallery/credits
    defaults:
        _controller: Madcoders\SyliusTaxonGalleryPlugin\Controller\CreditsController
