# Sylius TaxonGallery Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>

madcoders_sylius_taxon_gallery_plugin_shop:
    resource: "@MadcodersSyliusTaxonGalleryPlugin/Resources/config/routing/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

madcoders_sylius_taxon_gallery_plugin_admin:
    resource: "@MadcodersSyliusTaxonGalleryPlugin/Resources/config/routing/admin_routing.yaml"
    prefix: /admin
